//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace routing_server.JCDecauxProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JCDecauxProxy.IJCDecauxService")]
    public interface IJCDecauxService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxService/GetContracts", ReplyAction="http://tempuri.org/IJCDecauxService/GetContractsResponse")]
        string GetContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxService/GetContracts", ReplyAction="http://tempuri.org/IJCDecauxService/GetContractsResponse")]
        System.Threading.Tasks.Task<string> GetContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxService/GetStations", ReplyAction="http://tempuri.org/IJCDecauxService/GetStationsResponse")]
        string GetStations(string contractName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxService/GetStations", ReplyAction="http://tempuri.org/IJCDecauxService/GetStationsResponse")]
        System.Threading.Tasks.Task<string> GetStationsAsync(string contractName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxService/GetStationInfo", ReplyAction="http://tempuri.org/IJCDecauxService/GetStationInfoResponse")]
        string GetStationInfo(string contractName, int stationNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxService/GetStationInfo", ReplyAction="http://tempuri.org/IJCDecauxService/GetStationInfoResponse")]
        System.Threading.Tasks.Task<string> GetStationInfoAsync(string contractName, int stationNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJCDecauxServiceChannel : routing_server.JCDecauxProxy.IJCDecauxService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JCDecauxServiceClient : System.ServiceModel.ClientBase<routing_server.JCDecauxProxy.IJCDecauxService>, routing_server.JCDecauxProxy.IJCDecauxService {
        
        public JCDecauxServiceClient() {
        }
        
        public JCDecauxServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JCDecauxServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetContracts() {
            return base.Channel.GetContracts();
        }
        
        public System.Threading.Tasks.Task<string> GetContractsAsync() {
            return base.Channel.GetContractsAsync();
        }
        
        public string GetStations(string contractName) {
            return base.Channel.GetStations(contractName);
        }
        
        public System.Threading.Tasks.Task<string> GetStationsAsync(string contractName) {
            return base.Channel.GetStationsAsync(contractName);
        }
        
        public string GetStationInfo(string contractName, int stationNumber) {
            return base.Channel.GetStationInfo(contractName, stationNumber);
        }
        
        public System.Threading.Tasks.Task<string> GetStationInfoAsync(string contractName, int stationNumber) {
            return base.Channel.GetStationInfoAsync(contractName, stationNumber);
        }
    }
}
