//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace routing_server.JCDecauxService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/proxy_cache_server.Implementation")]
    public partial class Contract : object
    {
        
        private string[] citiesField;
        
        private string commercial_nameField;
        
        private string country_codeField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] cities
        {
            get
            {
                return this.citiesField;
            }
            set
            {
                this.citiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string commercial_name
        {
            get
            {
                return this.commercial_nameField;
            }
            set
            {
                this.commercial_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country_code
        {
            get
            {
                return this.country_codeField;
            }
            set
            {
                this.country_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/proxy_cache_server.Implementation")]
    public partial class Station : object
    {
        
        private string addressField;
        
        private int available_bike_standsField;
        
        private int available_bikesField;
        
        private bool bankingField;
        
        private int bike_standsField;
        
        private bool bonusField;
        
        private string contract_nameField;
        
        private long last_updateField;
        
        private string nameField;
        
        private int numberField;
        
        private routing_server.JCDecauxService.Position positionField;
        
        private string statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int available_bike_stands
        {
            get
            {
                return this.available_bike_standsField;
            }
            set
            {
                this.available_bike_standsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int available_bikes
        {
            get
            {
                return this.available_bikesField;
            }
            set
            {
                this.available_bikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool banking
        {
            get
            {
                return this.bankingField;
            }
            set
            {
                this.bankingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bike_stands
        {
            get
            {
                return this.bike_standsField;
            }
            set
            {
                this.bike_standsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bonus
        {
            get
            {
                return this.bonusField;
            }
            set
            {
                this.bonusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contract_name
        {
            get
            {
                return this.contract_nameField;
            }
            set
            {
                this.contract_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long last_update
        {
            get
            {
                return this.last_updateField;
            }
            set
            {
                this.last_updateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public routing_server.JCDecauxService.Position position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/proxy_cache_server.Implementation")]
    public partial class Position : object
    {
        
        private double latField;
        
        private double lngField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat
        {
            get
            {
                return this.latField;
            }
            set
            {
                this.latField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lng
        {
            get
            {
                return this.lngField;
            }
            set
            {
                this.lngField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="routing_server.JCDecauxService.IJCDecauxService")]
    public interface IJCDecauxService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxService/GetContracts", ReplyAction="http://tempuri.org/IJCDecauxService/GetContractsResponse")]
        System.Threading.Tasks.Task<routing_server.JCDecauxService.Contract[]> GetContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxService/GetStations", ReplyAction="http://tempuri.org/IJCDecauxService/GetStationsResponse")]
        System.Threading.Tasks.Task<routing_server.JCDecauxService.Station[]> GetStationsAsync(string contractName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IJCDecauxServiceChannel : routing_server.JCDecauxService.IJCDecauxService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class JCDecauxServiceClient : System.ServiceModel.ClientBase<routing_server.JCDecauxService.IJCDecauxService>, routing_server.JCDecauxService.IJCDecauxService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public JCDecauxServiceClient() : 
                base(JCDecauxServiceClient.GetDefaultBinding(), JCDecauxServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IJCDecauxService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JCDecauxServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(JCDecauxServiceClient.GetBindingForEndpoint(endpointConfiguration), JCDecauxServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JCDecauxServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(JCDecauxServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JCDecauxServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(JCDecauxServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JCDecauxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<routing_server.JCDecauxService.Contract[]> GetContractsAsync()
        {
            return base.Channel.GetContractsAsync();
        }
        
        public System.Threading.Tasks.Task<routing_server.JCDecauxService.Station[]> GetStationsAsync(string contractName)
        {
            return base.Channel.GetStationsAsync(contractName);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IJCDecauxService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IJCDecauxService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/proxy_cache_server/JCDecauxService/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return JCDecauxServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IJCDecauxService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return JCDecauxServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IJCDecauxService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IJCDecauxService,
        }
    }
}
